# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider :hyperv do |v|
        v.vmname  = "atomic-sftp" 
    end

    config.vm.hostname = "atomic-sftp"
    config.vm.network "public_network"
    config.vm.provider "hyperv"
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "./../../", "/vagrant", type: "smb"
    config.vm.provision :shell, path: "./../provision.sh"

    config.vm.network "forwarded_port", guest: 8090, host: 8090
    config.vm.network "forwarded_port", guest: 8091, host: 8091

end